name: Auto Run

on:
  schedule:
    - cron: 0 */2 * * *
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      GROQ_API_KEY: ${{ secrets.GROQ_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - run: pip install -r rec.txt

      - run: python summarizer.py
